apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app1
  name: springboot-app1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app1
  template:
    metadata:
      labels:
        app: springboot-app1
    spec:
      containers:
      - name: my-springboot-app1
        image: 946906550848.dkr.ecr.ap-south-1.amazonaws.com/spring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app1
    k8s-app: springboot-app1
  name: springboot-app1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app1
